const constKeys={
    navBar: {
        formLabel: "Sign in",
        loginLabel: "Login",
        signUpLabel: "Sign up",
        registerLabel: "Register",
        logoutLabel: "Logout",
        homeLabel: "Home",
        profile: "Profile",
        myListing: "My Listing",
        housing: "Housing",
        myBooking: "My Wishlist",
        postProperty: "Post Property"
    },
    name:"name",
    userName:"userName",
    password:"password",
    email:"email",
    userId:"userId",
    formLabel:"Sign in",
    loginLabel:"Login",
    signUpLabel:"Sign up",
    registerLabel:"Register",
    filter:"Filters",
    builtUpArea:"BuiltUpArea",
    deposit:"Deposit",
    rent:"Rent",
    squareFeet:"Sq.Ft",
    parking:"Parking",
    furnish:"Furnishing",
    buildingAge:"Age of Building",
    internet:"Internet Service",
    yes:"yes",
    no:"no",
    NA:"NA",
    pool:"Swimming Pool",
    elevator:"Lift",
    powerBackup:"Power backUp",
    AC:"Air conditionor",
    apartmentType:"Apartment type",
    tenant:"Preffered Tenants",
    availability:"Availability",
    bhk1:"1 BHK",
    bhk2:"2 BHK",
    bhk3:"3 BHK",
    bhk4:"4 BHK",
    overView:"Overview",
    description:"Description",
    name1:"Name",
    email1:"Email",
    Ok:"ok",
    family:"Family",
    bachelor:"Bachelor",
    single:"Single",
    girls:"Girls",
    boys:"Boys",
    full:"Full",
    semi:"Semi",
    none:"None",
    rentRange:"Rent range",

}
export default constKeys;